views:
  - cards:
      - type: custom:fluid-progressbar-card
        name: Fluid Progress Bar Card
        entity: input_number.battery_evel
        test_gui: true
      - type: entities
        entities:
          - input_number.battery_level
