name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      # Build
      - name: Build the file
        run: |
          npm ci
          npm run build
          ls

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/fluid-progressbar-card.js
          asset_name: fluid-progressbar-card.js
          tag: ${{ github.ref }}
          overwrite: true
